package com.boot.designsystem.theme.material

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006d37)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF9bf7b2)
val md_theme_light_onPrimaryContainer = Color(0xFF00210b)
val md_theme_light_secondary = Color(0xFF506353)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd3e8d3)
val md_theme_light_onSecondaryContainer = Color(0xFF0d1f12)
val md_theme_light_tertiary = Color(0xFF3a656f)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbeeaf5)
val md_theme_light_onTertiaryContainer = Color(0xFF001f25)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdf7)
val md_theme_light_onBackground = Color(0xFF1a1c1a)
val md_theme_light_surface = Color(0xFFfbfdf7)
val md_theme_light_onSurface = Color(0xFF1a1c1a)
val md_theme_light_surfaceVariant = Color(0xFFdde4da)
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFF727971)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1ec)
val md_theme_light_inverseSurface = Color(0xFF2f312e)
val md_theme_light_inversePrimary = Color(0xFF7fd997)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF7fd997)
val md_theme_dark_onPrimary = Color(0xFF003918)
val md_theme_dark_primaryContainer = Color(0xFF005226)
val md_theme_dark_onPrimaryContainer = Color(0xFF9bf7b2)
val md_theme_dark_secondary = Color(0xFFb6ccb7)
val md_theme_dark_onSecondary = Color(0xFF223526)
val md_theme_dark_secondaryContainer = Color(0xFF394b3c)
val md_theme_dark_onSecondaryContainer = Color(0xFFd3e8d3)
val md_theme_dark_tertiary = Color(0xFFa2ced9)
val md_theme_dark_onTertiary = Color(0xFF01363f)
val md_theme_dark_tertiaryContainer = Color(0xFF214d56)
val md_theme_dark_onTertiaryContainer = Color(0xFFbeeaf5)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c1a)
val md_theme_dark_onBackground = Color(0xFFe2e3de)
val md_theme_dark_surface = Color(0xFF1a1c1a)
val md_theme_dark_onSurface = Color(0xFFe2e3de)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFc1c9bf)
val md_theme_dark_outline = Color(0xFF8b938a)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1a)
val md_theme_dark_inverseSurface = Color(0xFFe2e3de)
val md_theme_dark_inversePrimary = Color(0xFF006d37)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF006d37)
val error = Color(0xFFba1b1b)